gui:
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
  mouseEvents: true
  skipStashWarning: true
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    signOff: false
  merging:
    manualCommit: false
    args: ""
  log:
    showGraph: always
    showWholeGraph: false
os:
  editCommand: "nvim"
  editCommandTemplate: "{{editor}} {{filename}}"
  openCommand: "open {{filename}}"
